query($filters: LessonFiltersInput) {
  lessons(filters: $filters) {
    id
    description
    title
    category {
      title
    }
    level {
      title
    }
    chapter {
      title
    }
  }
}
